#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/etc/init.d/activemq
### BEGIN INIT INFO
# Provides: activemq
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Controls Apache Activemq as a Service
### END INIT INFO

# Example of a very simple *nix init script that delegates commands to the bin/activemq script
# Typical usage is to do:
#
#   cp bin/init.d/activemq /etc/init.d/activemq
#   chmod 755 /etc/init.d/activemq
#   chown root:root /etc/init.d/activemq
#   update-rc.d activemq defaults
#   update-rc.d activemq enable

# Where you extracted the Activemq distribution bundle
ACTIVEMQ_DIR="@@ansible_activemq_dir@@"
JAVA_HOME="@@ansible_java_home@@"

if [ ! -d "$ACTIVEMQ_DIR" ]; then
  echo "$ACTIVEMQ_DIR not found! Please check the ACTIVEMQ_DIR setting in your $0 script."
  exit 1
fi

# Specify the user to run Activemq as; if not set, then Solr will run as root.
# Running Activemq as root is not recommended for production environments
RUNAS="@@ansible_activemq_user@@"

# verify the specified run as user exists
runas_uid="`id -u "$RUNAS"`"
if [ $? -ne 0 ]; then
  echo "User $RUNAS not found! Please create the $RUNAS user before running this script."
  exit 1
fi

run_command() {
  echo "Running command -> $1"
  if [ -n "$RUNAS" ]; then
    su -c "export JAVA_HOME=$JAVA_HOME ; \"$ACTIVEMQ_DIR/bin/activemq\" $1" - "$RUNAS"
  else
    export JAVA_HOME=$JAVA_HOME ; "$ACTIVEMQ_DIR/bin/activemq" "$1"
  fi
}

case "$1" in
  start)
    run_command "start"
    ;;
  restart)
    run_command "stop"
    run_command "start"
    ;;
  stop|status)
    run_command "$1"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit
esac
