- name: Create alfresco user
  user:
    name: "{{ alfresco_user }}"
    shell: /bin/bash
    password: "{{ alfresco_user_password }}"
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_rsa"

- name: Create alfresco folder
  file:
    path: "{{ alfresco_root_dir }}"
    state: directory
    mode: 0755
    owner: "{{ alfresco_user }}"
    group: "{{ alfresco_group }}"

- name: Unzip alfresco-content-services-distribution-6.1.0.zip
  unarchive:
    src: '{{ provision_files_path }}/downloaded/alfresco-content-services-distribution-6.1.0.zip'
    dest: "{{ alfresco_root_dir }}"
    remote_src: yes
    owner: "{{ alfresco_user }}"
    group: "{{ alfresco_group }}"
    creates: '{{ alfresco_root_dir }}/web-server/webapps/alfresco.war'

- name: Creates other Alfresco folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ alfresco_user }}"
    group: "{{ alfresco_group }}"
  with_items:
    - "{{ alfresco_root_dir }}/modules/platform"
    - "{{ alfresco_root_dir }}/modules/share"
    - "{{ alfresco_root_dir }}/alf_data/contentstore"
    - "{{ alfresco_root_dir }}/alf_data/contentstore.deleted"
    - "{{ alfresco_root_dir }}/alf_data/solr6Backup/alfresco"
    - "{{ alfresco_root_dir }}/alf_data/solr6Backup/archive"
    - "{{ alfresco_root_dir }}/scripts"
    - "{{ alfresco_root_dir }}/jre-1.8.0_25"

- name: Install ImageMagick
  yum:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - '{{ provision_files_path }}/downloaded/imagemagick-distribution-7.0.7-27-libs-linux.rpm'
      - '{{ provision_files_path }}/downloaded/imagemagick-distribution-7.0.7-27-linux.rpm'

- name: unzip LibreOffice
  unarchive:
    src: '{{ provision_files_path }}/downloaded/libreoffice-dist-5.4.6-linux.gz'
    dest: "{{ provision_files_path }}"
    remote_src: yes
    owner: "{{ alfresco_user }}"
    group: "{{ alfresco_group }}"
    creates: '{{ provision_files_path }}/LibreOffice_5.4.6.2_Linux_x86-64_rpm'

- name: install LibreOffice in temporary location
  command: '{{ provision_files_path }}/LibreOffice_5.4.6.2_Linux_x86-64_rpm/install \
      {{ provision_files_path }}/LibreOffice_5.4.6.2_Linux_x86-64_rpm {{ provision_files_path }}'
  become_user: "{{ alfresco_user }}"
  become: yes
  args:
    creates: '{{ provision_files_path }}/opt/libreoffice5.4'

- name: copy Libreoffice to Alfresco folder
  synchronize:
    src: '{{ provision_files_path }}/opt/libreoffice5.4'
    dest: "{{ alfresco_root_dir }}"
    owner: yes
    group: yes
    recursive: yes
  delegate_to: 127.0.0.1

- name: Untar alfresco-pdf-renderer
  unarchive:
    src: "{{ alfresco_root_dir }}/alfresco-pdf-renderer/alfresco-pdf-renderer-1.1-linux.tgz"
    dest: "{{ alfresco_root_dir }}/alfresco-pdf-renderer"
    remote_src: yes
    owner: "{{ alfresco_user }}"
    group: "{{ alfresco_group }}"
    creates: "{{ alfresco_root_dir }}/alfresco-pdf-renderer/alfresco-pdf-renderer"
  register: alfresco_pdf_renderer

- name: Clean alfresco-pdf-renderer files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ alfresco_root_dir }}/alfresco-pdf-renderer/alfresco-pdf-renderer-1.1-linux.tgz"
    - "{{ alfresco_root_dir }}/alfresco-pdf-renderer/alfresco-pdf-renderer-1.1-win64.tgz"
  when: alfresco_pdf_renderer.failed == false

- name: Untar java (openjdk 11.0.1)
  unarchive:
    src: "{{ provision_files_path }}/downloaded/openjdk-11.0.1_linux-x64_bin.tar.gz"
    dest: "{{ alfresco_root_dir }}"
    remote_src: yes
    creates: "{{ alfresco_root_dir }}/jdk-11.0.1"
  register: jdk_folder
  become_user: "{{ alfresco_user }}"
  become: yes

- name: Untar java (Jre 1.8)
  unarchive:
    src: "{{ provision_files_path }}/downloaded/jre-1.8.0_25-linux.tgz"
    dest: "{{ alfresco_root_dir }}/jre-1.8.0_25/"
    remote_src: yes
    creates: "{{ alfresco_root_dir }}/jre-1.8.0_25/bin/java"
    extra_opts: [--strip-components=1]
  become_user: "{{ alfresco_user }}"
  become: yes

- name: Create java folder link
  file:
    src: "{{ alfresco_root_dir }}/jdk-11.0.1"
    dest: "{{ alfresco_root_dir }}/java"
    state: link
    owner: "{{ alfresco_user }}"
    group: "{{ alfresco_group }}"
  when: jdk_folder.failed == false
